### ISSUE TITLE
[p2p] Improvement code

### ISSUE THREAD

**Issue by Alondra87** [JoffreyNK/To-Do-List#2]
<h2>Hello @JoffreyNK 😀</h2>
Good work on your code
<h2>To highlight🎯</h2>
<ul>
<li>✔️ No linter errors</li>
<li>✔️ organized code </li>
<li>✔️ Nice design</li>
</ul>
<img src="https://media4.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif"/>
<h2>Suggestions✍️</h2> 
✏In order to improve your code we suggest you add a placeholder for the accessibility of the user in the input;

https://github.com/JoffreyNK/To-Do-List/blob/e05053422698181d667884a33bb8e69feb16ee9c/src/index.html#L12

✏ You could kindly add an id to identify the correct checkbox checked to change the state to true.

https://github.com/JoffreyNK/To-Do-List/blob/e05053422698181d667884a33bb8e69feb16ee9c/src/modules/managedata.js#L74-L80

**Comment by joffreynk** [comment]
solved
