### ISSUE TITLE
Code Review With Partner

### ISSUE THREAD

**Issue by Ibnballo1** [JoffreyNK/To-Do-List#6]
@Ibnballo1

- kindly correct the sentence. Use 'your' instead of 'you'.
- Kindly use the correct link for the live demo so that people can test your site.
- Please use HTML 5 syntax to organize your code, like using the <main>, <section>, etc. This will ensure that your site is well accessible.
- It will be good if you adopt using responsive units instead of fixed units as this will make your site more responsive.
- You should try to always make your code DRY so that there will be repetition and this will save you time and energy if you want to fix bug(s)
-

**Comment by joffreynk** [comment]
all issues fixed
